# Generated by Django 3.1.2 on 2020-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=10)),
                ('destination_id', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('graph_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VertexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('graph_id', models.CharField(max_length=20)),
            ],
        ),
    ]
